name: "My First Workflow"
run-name : "My First Run"

on: [push]
jobs: #a workflow run is made up of one or more jobs, which run in parallel by default
  build:
    runs-on: ubuntu-latest #provided and managed by github
    steps:
    - name: "Checkout"
      uses: actions/checkout@v6 #checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      with:
        fetch-depth: 0 #fetch all history for all branches and tags
    - name: "One code line script"
      run: echo "Hello, world!"
    - name: "Multi-line script"
      run: |
        echo "This is the first line"
        echo "Add other actions to build, test, and deploy your project."
        echo "See https://help.github.com/actions for more information about GitHub Actions."
    - name: "Last line script"
      run: echo "This is the last line of the multi-line script"
      

  test:
    runs-on: ubuntu-latest #provided and managed by github
    steps:
      - name: "Checkout- code"
        uses: actions/checkout@v6 #checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        with:
          fetch-depth: 0 #fetch all history for all branches and tags
      - name: "Checking multiple lines of run code"
        run: echo "This is the first line of the test job - multi line script"
      - run: echo "This is the second line of the test job - multi line script"
      - run: echo "This is the third line of the test job- multi line script"

  Explore-GitHub-Actions:
    runs-on: ubuntu-latest #provided and managed by github
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code #checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 #fetch all history for all branches and tags
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."